Add pooling rate timer
KYRDTeam/Krystal-iOS pull request #216
Opened 2021-09-15 08:44 UTC by MrQKyber

2021-09-16 04:49 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +    self.startRateTimer()
We could hide the `SRCountdownTimer` when amount changed and show it when completing

2021-09-16 04:49 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +    self.stopRateTimer()
If a user just open the select token dialog but don't select any token and close the dialog, the counter must not stop because the source/dest token desn't change

2021-09-16 09:46 UTC, MrQKyber commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +    self.stopRateTimer()
Counter doesn't stop when dismiss token select view, It is stopped when user select an token

2021-09-16 10:47 UTC, toidv requested changes

2021-09-16 10:47 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +    self.startRateTimer()
With this condition, the counter only shows when user clicks on done from the keyboard. If user doesn't close the keyboard the counter could not start. Please also display counter even keyboard not close. You could refer 1Inch wallet for the behavior

2021-09-16 10:47 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +  fileprivate func startRateTimer() {
Please startRateTimer when switching source/dest token (`swapButtonPressed`). Because pair was changed

2021-09-16 15:47 UTC, MrQKyber commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +    self.startRateTimer()
added this behavior

2021-09-16 15:47 UTC, MrQKyber commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/NewDesign/Controller/KSwapViewController.swift
> +  fileprivate func startRateTimer() {
it's done

2021-09-17 02:57 UTC, toidv approved these changes
LGTM

2021-09-17 03:34 UTC, merged