Integrate avalanche
KYRDTeam/Krystal-iOS pull request #227
Opened 2021-09-23 10:10 UTC by MrQKyber

2021-09-23 10:52 UTC, toidv commented on KyberNetwork/Settings/Types/Constants.swift
> +    endpoint: "https://speedy-nodes-nyc.moralis.io/847df1933775fb519982918b/avalanche/mainnet/",
Please use this one as primary node: https://api.avax.network/ext/bc/C/rpc. The node https://speedy-nodes-nyc.moralis.io/847df1933775fb519982918b/avalanche/mainnet/ is just temporary solution

2021-09-24 03:45 UTC, toidv requested changes

2021-09-24 03:45 UTC, toidv commented on KyberNetwork/KyberNetwork/Networking/External/KNGeneralProvider.swift
> +      return "There.is.a.difference.between.the.estimated.price.matic" //TODO: wait for avalance
Please change it accordingly to `Coingecko, and Pangolin`

2021-09-24 03:45 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.xib
> +        <array key="Karla-VariableFont_wght.ttf">
It is correct font?

2021-09-24 03:45 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift
> +    let otherTokenMatic: TokenObject = token.isMatic ? KNSupportedTokenStorage.shared.usdceToken : KNSupportedTokenStorage.shared.maticToken
usdce for Matic seems incorrect

2021-09-24 03:45 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/KyberSwap/SwapVC/Coordinator/KNExchangeTokenCoordinator.swift
> +    let otherTokenAvax: TokenObject = token.isAvax ? KNSupportedTokenStorage.shared.usdcToken : KNSupportedTokenStorage.shared.avaxToken
usdce?

2021-09-24 04:08 UTC, MrQKyber commented on KyberNetwork/KyberNetwork/Screens/Tabbars/Earn/Controllers/EarnMenuViewController.xib
> +        <array key="Karla-VariableFont_wght.ttf">
Xcode auto change font in xib file. It is okay

2021-09-24 04:41 UTC, toidv approved these changes
LGTM

2021-09-24 04:42 UTC, merged