[iOS] - Update Earn swap screen info
KYRDTeam/Krystal-iOS pull request #293
Opened 2021-12-06 07:42 UTC by thangpham26394

RE #KRYS-1755

2021-12-14 04:10 UTC, MrQKyber requested changes
Overlap text min receive amount in earn swap confirm view

2021-12-14 09:29 UTC, MrQKyber approved these changes
LGTM

2021-12-15 08:05 UTC, toidv commented
Please resolve conflicts

2021-12-17 07:08 UTC, toidv approved these changes

2021-12-17 07:08 UTC, merged