[KRYS-2104] Dapp browser feature
KYRDTeam/Krystal-iOS pull request #315
Opened 2022-01-04 07:46 UTC by MrQKyber

2022-01-12 11:06 UTC, toidv requested changes

2022-01-12 11:06 UTC, toidv commented on KyberNetwork/Browser/Types/EIP712TypedData.swift
> +    /// Helper func for `encodeData`
Please clean up code

2022-01-12 11:06 UTC, toidv commented on KyberNetwork/EtherClient/EthTypedData.swift
> +//    var typedData: Data {
Please clean up comments

2022-01-12 11:12 UTC, toidv commented on KyberNetwork/KyberNetwork/Screens/Tabbars/Invest/Controllers/BrowserOptionsViewController.swift
> +      self.forwardButton.backgroundColor = .white.withAlphaComponent(0.5)
Please use 0.4 alpha with the current background not the white one

2022-01-13 03:03 UTC, MrQKyber commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
I re-request nonce before sending tx, this code is for parsing json response from javascript

2022-01-13 03:05 UTC, MrQKyber commented on KyberNetwork/Browser/Types/DappAction.swift
> +      guard let value = object["gasLimit"]?.value ?? object["gas"]?.value else { return .none }
which value should assign to gas limit when response from javascript is invalid

2022-01-13 03:53 UTC, toidv commented on KyberNetwork/Browser/Types/DappAction.swift
> +      guard let value = object["gasLimit"]?.value ?? object["gas"]?.value else { return .none }
we need estimate gasLimit from note

2022-01-13 03:54 UTC, toidv commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
So just return `.none` like else case

2022-01-13 04:27 UTC, MrQKyber commented on KyberNetwork/Browser/Types/DappAction.swift
> +      guard let value = object["gasLimit"]?.value ?? object["gas"]?.value else { return .none }
I will set an default value for token exchange for avoid to many async task for tx

2022-01-13 04:28 UTC, MrQKyber commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
It 'd better to keep the nonce parsing logic for later use

2022-01-17 03:13 UTC, toidv commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
not sure when will you use this logic?

2022-01-17 03:27 UTC, MrQKyber commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
I think I will use for validate nonce if needed, or in case if our app can get nonce from node. Currently there isn't any case user can not get nonce, so just keep the value here and override it later

2022-01-17 04:12 UTC, toidv approved these changes

2022-01-17 04:38 UTC, toidv requested changes
Please update logic for sign ethereum type message

2022-01-18 04:06 UTC, toidv commented on KyberNetwork/Browser/Types/DappAction.swift
> +    let nonce: BigInt? = {
Don't use nonce from outside of app, if can't get nonce, then display error. Please remove it

2022-01-18 09:20 UTC, toidv commented on KyberNetwork/Browser/Factory/WKWebViewConfiguration.swift
> +        let whiteListedUrls = [
Please remove this logic

2022-01-18 09:24 UTC, toidv commented on KyberNetwork/Browser/Types/EIP712TypedData.swift
> +//    var domainVerifyingContract: AlphaWallet.Address? {
Please clean up

2022-01-20 04:34 UTC, merged