[iOS] Integrate Aurora chain
KYRDTeam/Krystal-iOS pull request #408
Opened 2022-03-30 09:15 UTC by thangpham26394

RE #KRYS-2734

2022-03-30 10:38 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Coordinators/InternalCoordinators/RateCoordinator/KNRateCoordinator.swift
> +    var allChainQuote: [String] = ["btc", "usd"]
Can move this variable as a class property and refactor a bit
`let allChainQuote: [String] = (["btc", "usd"] + ChainType.allCases.map { $0.quoteToken() }).unique`

2022-03-30 10:40 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Configurations/Environments/Sources/KNEnvironment.swift
> +    var allChainPath: [String] = []
Can be shorten 

```
static var allChainPath: String? {
    return ChainType.allCases
      .map { chain in chain.currentChainPathName() }
      .joined(separator: ",")
  }

```

2022-03-30 10:42 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Networking/External/ChainType.swift
> +  func currentChainPathName() -> String {
It should be `apiChainPath`, not current chain path name.

2022-03-30 11:43 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Screens/CommonViews/SwitchChain/SwitchChainViewController.swift
> +    self.tableView.register(nib, forCellReuseIdentifier: SwitchChainCell.kCellID)
The cell registration can use [this extension](https://github.com/KYRDTeam/Krystal-iOS/pull/410)

2022-03-30 11:43 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Coordinators/BalanceCoordinator/KNLoadBalanceCoordinator.swift
> +        ChainType.allCases.forEach { chain in
Can use `.map` function like below

2022-03-30 11:47 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Networking/External/ChainType.swift
> +    return chainType
This can be shorten
```
return ChainType.allCases.first { $0.getChainId() == chainID }
```

2022-03-30 11:47 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Screens/CommonViews/SwitchChain/SwitchChainCell.swift
> +  override func setSelected(_ selected: Bool, animated: Bool) {
Please remove unused functions

2022-03-31 03:43 UTC, MrQKyber requested changes
Crash when unwrap network address
Need merge main branch into this branch to solve conflict

2022-03-31 06:37 UTC, tungnguyen20 commented on KyberNetwork/KyberNetwork/Screens/CommonViews/SwitchChain/SwitchChainViewController.swift
> +    ) as! SwitchChainCell
Can use `let cell = tableView.dequeueReusableCell(SwitchChainCell.self, indexPath: indexPath)` without extra cellID and casting.

2022-03-31 08:29 UTC, toidv commented on KyberNetwork/KyberNetwork/Networking/External/ChainType.swift
> +    case .eth, .arbitrum:
Please add aurora

2022-03-31 09:51 UTC, toidv approved these changes

2022-03-31 09:51 UTC, merged